### PR TITLE
fix: Fixed `toml_diff_check` printing, `diff._strict_diff_ .change_flags()` function

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
# Description

Fixed some minor issue which affects on the correct representation of the tool diff checks

### CODE REVIEW

**Review by FelipeRosa — APPROVED** [review]
LGTM

**Review by bkioshn — APPROVED** [review]

**Review by bkioshn — CHANGES_REQUESTED** [review]
If I'm not mistaken, there is a issue with the color too right? 🤔

**Review by apskhem — COMMENTED** [review]
Looks fine

**Review by kukkok3 — APPROVED** [review]
LGTM

**Comment by Mr-Leshiy** [comment]
@bkioshn Yea, exactly, it solves this issue.

**Review by bkioshn — APPROVED** [review]

**Pull request merged**
