### PR TITLE
fix: update earthly to 0.8

### LINKED ISSUE #167: 🛠️ [TASK] : Bump earthly version to `v0.8`
### Summary

Bump Earthly version to [0.8.0](https://github.com/earthly/earthly/releases/tag/v0.8.0)

### Description

After everyone in the team will update earthly locally do the following:
- Update each Earthfile in our repos from `VERSION 0.7` to `VERSION 0.8`
- remove unstable flags as `--arg-scope-and-set`, `--cache-persist-option`, `--git-refs`, `--global-cache`,  `--no-network `, `--pass-args`,  `--use-docker-ignore`, `--use-function-keyword`,  `--use-visited-upfront-hash-collection`.

In addition, fix the import style from 

```Earthfile
VERSION 0.8

package:
    FROM +build
    COPY ./artifact pkg
    COPY ../other_project+build/artifact pkg
```
to 
```Earthfile
VERSION 0.8

IMPORT ../other_project as other-project 

package:
    FROM +build
    COPY ./artifact pkg
    COPY other-project+build/artifact pkg
```

update the following repos:
- [catalyst-ci](https://github.com/input-output-hk/catalyst-ci)
- [hermes](https://github.com/input-output-hk/hermes)
- [catalyst-voices](https://github.com/input-output-hk/catalyst-voices)

### PR DESCRIPTION
**Pull request by bkioshn**
# Description

Update Earthly from 0.7 to 0.8

## Related Issue(s)

Closes #167

## Description of Changes

- Update Earthly from 0.7 to 0.8
- Fix earthly cache https://docs.earthly.dev/docs/earthfile#cache
- Update `ginkgo` version
- Update related docs

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Comment by FelipeRosa** [comment]
@bkioshn I'm wondering because I didn't have time to test it yet but does this affect the other repos that use the CI images?

Asking this because the files there are on version `0.7` but I assume it's backwards compatible.

**Comment by bkioshn** [comment]
> @bkioshn I'm wondering because I didn't have time to test it yet but does this affect the other repos that use the CI images?
> 
> Asking this because the files there are on version `0.7` but I assume it's backwards compatible.

Sorry, I was testing on my local machine, but here is the test for hermes @FelipeRosa 
https://github.com/input-output-hk/hermes/actions/runs/8710637328/job/23892974399

**Comment by FelipeRosa** [comment]
No problem! I was just wondering about that. Thanks for the test.

**Review by FelipeRosa — APPROVED** [review]
LGTM

**Review by Mr-Leshiy — APPROVED** [review]
LGTM

**Pull request merged**
